package monetdb.domain.monitordb;

import java.util.Date;

public class HistoryAI {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitordb.history_ai.id
     *
     * @mbggenerated Mon Jan 16 10:15:35 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitordb.history_ai.ts
     *
     * @mbggenerated Mon Jan 16 10:15:35 CST 2017
     */
    private Date ts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitordb.history_ai.value
     *
     * @mbggenerated Mon Jan 16 10:15:35 CST 2017
     */
    private Double value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitordb.history_ai.id
     *
     * @return the value of monitordb.history_ai.id
     *
     * @mbggenerated Mon Jan 16 10:15:35 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitordb.history_ai.id
     *
     * @param id the value for monitordb.history_ai.id
     *
     * @mbggenerated Mon Jan 16 10:15:35 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitordb.history_ai.ts
     *
     * @return the value of monitordb.history_ai.ts
     *
     * @mbggenerated Mon Jan 16 10:15:35 CST 2017
     */
    public Date getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitordb.history_ai.ts
     *
     * @param ts the value for monitordb.history_ai.ts
     *
     * @mbggenerated Mon Jan 16 10:15:35 CST 2017
     */
    public void setTs(Date ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitordb.history_ai.value
     *
     * @return the value of monitordb.history_ai.value
     *
     * @mbggenerated Mon Jan 16 10:15:35 CST 2017
     */
    public Double getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitordb.history_ai.value
     *
     * @param value the value for monitordb.history_ai.value
     *
     * @mbggenerated Mon Jan 16 10:15:35 CST 2017
     */
    public void setValue(Double value) {
        this.value = value;
    }
}