package monetdb.mapper.monitordb;

import java.util.List;
import monetdb.domain.monitordb.HistoryAI;
import monetdb.domain.monitordb.HistoryAIExample;
import org.apache.ibatis.annotations.Param;

public interface HistoryAIMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitordb.history_ai
     *
     * @mbggenerated Mon Jan 16 10:15:35 CST 2017
     */
    int countByExample(HistoryAIExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitordb.history_ai
     *
     * @mbggenerated Mon Jan 16 10:15:35 CST 2017
     */
    int deleteByExample(HistoryAIExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitordb.history_ai
     *
     * @mbggenerated Mon Jan 16 10:15:35 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitordb.history_ai
     *
     * @mbggenerated Mon Jan 16 10:15:35 CST 2017
     */
    int insert(HistoryAI record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitordb.history_ai
     *
     * @mbggenerated Mon Jan 16 10:15:35 CST 2017
     */
    int insertSelective(HistoryAI record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitordb.history_ai
     *
     * @mbggenerated Mon Jan 16 10:15:35 CST 2017
     */
    List<HistoryAI> selectByExample(HistoryAIExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitordb.history_ai
     *
     * @mbggenerated Mon Jan 16 10:15:35 CST 2017
     */
    HistoryAI selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitordb.history_ai
     *
     * @mbggenerated Mon Jan 16 10:15:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") HistoryAI record, @Param("example") HistoryAIExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitordb.history_ai
     *
     * @mbggenerated Mon Jan 16 10:15:35 CST 2017
     */
    int updateByExample(@Param("record") HistoryAI record, @Param("example") HistoryAIExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitordb.history_ai
     *
     * @mbggenerated Mon Jan 16 10:15:35 CST 2017
     */
    int updateByPrimaryKeySelective(HistoryAI record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitordb.history_ai
     *
     * @mbggenerated Mon Jan 16 10:15:35 CST 2017
     */
    int updateByPrimaryKey(HistoryAI record);
}